### ISSUE TITLE
Fail to build on github for windows a package which doesn't have a msm file

### ISSUE THREAD

**Issue by rfcoder** [SmartExporter/.github#17]
Error:
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.Bash code:
# MSM: CLEAN+RESTORE+BUILD (WINDOWS)
if [ ${OSTYPE} = "msys" ] && [ -d "${MsmDir}" ]; then
    printf "Preparing MSM creation"
    cd "${MsmDir}"
    rm -rf {bin,obj}
    dotnet ${DotnetArgs} -t:restore ${MsBuildProps}
    dotnet ${DotnetArgs} -t:build ${MsBuildProps}
    printf "Finished MSM creation"
fi

Just as comment, it runs fine on local windows machine, on git hub works ok on linux, but give the above error for github windows

**Comment by SeArchitect** [comment]
Took me a while to find the problem. The `ci` script is correct. The problem is that we checkout `cwase.msm.cache` into `msm/cache` causing the `msm` directory to be created. I still need a solution.
